spring:
  application:
    name: service--booking-rental-platform
    version: "@project.version@"
  profiles:
    active: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db:DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 5000
  servlet:
    context-path: /service--booking-rental-platform

flyway:
  schemas: rentalplatform
  table: flyway-rental-platform

