spring:
  application:
    name: service--booking-rental-platform
    version: "@project.version@"
  profiles:
    active: dev

server:
  port: 5000
  servlet:
    context-path: /service--booking-rental-platform