CREATE TABLE IF NOT EXISTS PROPERTY_USER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    FULLNAME VARCHAR(100) NOT NULL,
    ROLE ENUM('OWNER', 'MANAGER', 'GUEST'),
    MAIL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
)