CREATE TABLE IF NOT EXISTS BLOCK (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    ID_PROPERTY INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_PROPERTY) REFERENCES PROPERTY (ID)
)