CREATE TABLE IF NOT EXISTS BOOKING (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS ENUM('CONFIRMED', 'CANCELED', 'FINISHED'),
    ID_GUEST INTEGER NOT NULL,
    ID_PROPERTY INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_GUEST) REFERENCES PROPERTY_USER (ID),
    FOREIGN KEY (ID_PROPERTY) REFERENCES PROPERTY (ID)
)