INSERT INTO PROPERTY_USER(FULL_NAME, ROLE, MAIL)
VALUES('John Doe', 'OWNER', 'john.doe@gmail.com');

INSERT INTO PROPERTY_USER(FULL_NAME, ROLE, MAIL)
VALUES('Mike Doe', 'GUEST', 'mike.doe@gmail.com');

INSERT INTO PROPERTY(NAME, ADDRESS, ID_OWNER)
VALUES('Village tiny house', '7st, nowhere', 1);

INSERT INTO PROPERTY(NAME, ADDRESS, ID_OWNER)
VALUES('Cozy apartment', 'Java Avenue, JavaLand', 1);

INSERT INTO BLOCK(START_DATE, END_DATE, ID_PROPERTY)
VALUES('2024-06-22', '2024-07-22', 2);

INSERT INTO BOOKING(START_DATE, END_DATE, STATUS, ID_GUEST, ID_PROPERTY)
VALUES('2024-03-22', '2024-07-22', 'CONFIRMED', 2, 1);