CREATE TABLE IF NOT EXISTS USER_PERMISSION (
    ID_USER INTEGER NOT NULL,
    ID_PERMISSION bigint(20) NOT NULL,
    PRIMARY KEY (ID_USER,ID_PERMISSION),
    FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
    FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSION (ID)
)